version = 0.1

[default.deploy.parameters]
stack_name = "tifactions"
resolve_s3 = true
s3_prefix = "tifactions"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "GitHubPagesUrl=\"https://lexpk/github.io/tofactions/\""
image_repositories = []

[default.global.parameters]
region = "eu-central-1"
